doctrine:
    dbal:
        #url: '%env(resolve:DATABASE_URL)%'
        dbname:                '%env(DATABASE_NAME_DEV)%'
        host:                   mysql_db
        port:                  '%env(DATABASE_PORT_DEV)%'
        user:                  '%env(DATABASE_USER_DEV)%'
        password:              '%env(DATABASE_PASSWORD_DEV)%'
        driver:                '%env(DATABASE_DRIVER_DEV)%'
        server_version:       13


# DATABASE_URL="mysql://phpmyadmin:55582555@mysql_db:3306/frenchCom?serverVersion=13&charset=utf8"

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '13'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
