version: '2.23.0'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile_Symfony
    depends_on:
      - mysql_db
    volumes:
      - .:/srv
  nginx_frenchom:
    image: drakona/nginx:8-symfony
    depends_on:
      - app
    volumes:
      - .:/srv
    ports:
      - "8000:80"
  mysql_db:
    image: 'bitnami/mysql:8.0.35'
    environment:      
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db-data:/bitnami/mysql
    ports:
      - "3308:3306"
volumes:
  db-data:


